project:
  type: website

website:
  title: "My Quarto Blog"
  description: "A blog powered by Quarto and hosted on GitHub Pages"
  navbar:
    right:
      - about.html
  output-dir: docs  # Ensure output is set to 'docs' for GitHub Pages

format:
  html:
    theme: cosmo
    toc: true
