project:
  type: website
  output-dir: docs  # Place this under the project key, not website

website:
  title: "My Quarto Blog"
  description: "A blog powered by Quarto and hosted on GitHub Pages"
  navbar:
    right:
      - about.html

format:
  html:
    theme: cosmo
    toc: true
