project:
  type: website
  output-dir: docs  # Ensure output is set to 'docs' for GitHub Pages

website:
  title: "Rachel Swallow"
  description: "A place where I organize my thoughts"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd  # Link to your About page
  
format:
  html:
    theme: simplex
    toc: true
